# Generated by Django 5.2.16 on 2026-07-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Tax percentage (e.g., 5.00 for 5% GST)', max_digits=5),
        ),
    ]
