# Generated by Django 5.2.16 on 2026-07-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_websitesetting_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code, without spaces or symbols (e.g. 919876543210 or 9876543210)', max_length=20, null=True),
        ),
    ]
