# Generated by Django 5.2.16 on 2026-07-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactinfo_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='google_map_iframe',
            field=models.TextField(blank=True, help_text='Paste the full iframe embed code from Google Maps', null=True),
        ),
    ]
