# Generated by Django 5.2.16 on 2026-07-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contactinfo_google_map_iframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Under ₹2000, ₹2000 - ₹4000', max_length=100)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price filter value. Leave blank for no minimum.', max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price filter value. Leave blank for no maximum.', max_digits=10, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which it will be displayed.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Budget Range',
                'verbose_name_plural': 'Budget Ranges',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
