# Generated by Django 5.2.16 on 2026-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_budgetrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='about_button_text',
            field=models.CharField(default='Read Our Full Story', help_text='Text to display on the action button.', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_button_url',
            field=models.CharField(default='/page/about-us/', help_text='URL / page link the button redirects to.', max_length=200),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_description',
            field=models.TextField(default='At Rangam Saradha Silk Sarees, each saree tells a story of artistic heritage, intricate handwork, and modern designs tailored for the contemporary Indian woman. From royal Kanchipurams to exquisite designer silks, we offer unmatched purity and premium luxury.', help_text='Detailed description of the brand/about section.'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Portrait image for the homepage About section.', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_subtitle',
            field=models.CharField(default='LEGACY OF ELEGANCE', help_text='Small subtitle label above the main heading.', max_length=100),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_title',
            field=models.CharField(default='About Rangam Saradha Silk Sarees', help_text='Main heading for the homepage About section.', max_length=150),
        ),
    ]
