# Generated by Django 5.2.16 on 2026-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_websitesetting_about_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Free Shipping', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. On orders over ₹1000', max_length=150, null=True)),
                ('icon_class', models.CharField(default='bi-truck', help_text='Bootstrap Icon class (e.g. bi-truck, bi-shield-check, bi-gem, bi-telephone)', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='bridal_banner_button_text',
            field=models.CharField(default='Shop Wedding Collection', help_text='Text on the banner button.', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='bridal_banner_button_url',
            field=models.CharField(default='/shop/?collection=bridal', help_text='URL the button links to.', max_length=200),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='bridal_banner_image',
            field=models.ImageField(blank=True, help_text='Background image for the bridal banner.', null=True, upload_to='bridal/'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='bridal_banner_subtitle',
            field=models.TextField(default='Exquisite handcrafted Kanchipuram bridal silk sarees designed for your special day.', help_text='Subtitle or description text.'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='bridal_banner_title',
            field=models.CharField(default='Bridal Collection', help_text='Title for the homepage bridal banner.', max_length=150),
        ),
    ]
