# Generated by Django 5.2.16 on 2026-07-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_whychooseus_websitesetting_bridal_banner_button_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whychooseus',
            old_name='subtitle',
            new_name='description',
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='why_choose_subtitle',
            field=models.CharField(default='THE RANGAM SARADHA PROMISE', help_text='Subtitle above the Why Choose Us heading.', max_length=150),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='why_choose_title',
            field=models.CharField(default='Why Choose Us', help_text='Main heading for the Why Choose Us section.', max_length=100),
        ),
    ]
