# Generated by Django 5.2.16 on 2026-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_subtitle_whychooseus_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload custom PNG/SVG icon image', null=True, upload_to='why_choose_us/'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='icon_class',
            field=models.CharField(blank=True, default='bi-truck', help_text='Bootstrap Icon class (e.g. bi-truck) OR PNG file path/URL', max_length=255),
        ),
    ]
