# Generated by Django 5.2.16 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_whychooseus_image_alter_whychooseus_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricCuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Banarasi, Kanchipattu, Organza', max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Upload card background image for this fabric curation', null=True, upload_to='fabric_curations/')),
                ('description', models.CharField(blank=True, help_text='Optional short description or subtitle', max_length=200, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fabric Curation',
                'verbose_name_plural': 'Fabric Curations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='fabric_curation_subtitle',
            field=models.CharField(default='SHOP BY MATERIAL', help_text='Subtitle above the Fabric Curations heading.', max_length=150),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='fabric_curation_title',
            field=models.CharField(default='Fabric Curations', help_text='Main heading for the Fabric Curations section.', max_length=100),
        ),
    ]
