# Generated by Django 5.2.16 on 2026-07-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_fabriccuration_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactSubmission',
            new_name='ContactMessage',
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
