# Generated by Django 5.2.16 on 2026-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_cod_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for this collection on the homepage.', null=True, upload_to='collections/'),
        ),
    ]
