# Generated by Django 5.2.16 on 2026-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Direct video file upload (MP4, WebM, MOV)', null=True, upload_to='product_videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
