# Generated by Django 5.2.16 on 2026-07-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_video_file_alter_product_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Direct video file upload (MP4, WebM, MOV)', max_length=500, null=True, upload_to='product_videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', max_length=500, null=True),
        ),
    ]
