# Generated by Django 5.2.16 on 2026-08-25 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('02:00 PM - 03:00 PM', '02:00 PM - 03:00 PM'), ('04:00 PM - 05:00 PM', '04:00 PM - 05:00 PM'), ('06:00 PM - 07:00 PM', '06:00 PM - 07:00 PM')], max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Specific requirements or questions for the call', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_bookings', to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Booking',
                'verbose_name_plural': 'Call Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
