# Generated by Django 5.2.16 on 2026-08-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_callbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('02:00 PM - 03:00 PM', '02:00 PM - 03:00 PM'), ('04:00 PM - 05:00 PM', '04:00 PM - 05:00 PM'), ('06:00 PM - 07:00 PM', '06:00 PM - 07:00 PM')], max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=20)),
                ('blocked_by_owner', models.BooleanField(default=False, help_text='Mark True to block this slot (owner unavailable/busy)')),
                ('notes', models.CharField(blank=True, help_text='Optional note / reason for blocking', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call Slot',
                'verbose_name_plural': 'Call Slots',
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
