"""
Django settings for rangam_saradha_silk project.

Generated by 'django-admin startproject' using Django 5.2.16.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT VARIABLES
# ============================================================

load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ.get("SECRET_KEY")

DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1")


ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost,testserver,rangamsaradhasilks.com,www.rangamsaradhasilks.com,.rangamsaradhasilks.com,rangam-saradha-silks.onrender.com"
    ).split(",")
    if host.strip()
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",

    # Cloudinary
    "cloudinary_storage",
    "cloudinary",

    # Third-party
    "phonenumber_field",
    "rest_framework",

    # Local apps
    "accounts.apps.AccountsConfig",
    "shop.apps.ShopConfig",
    "home.apps.HomeConfig",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise - static files
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # Custom middleware
    "home.middleware.SeparateSessionMiddleware",

    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Custom middleware
    "home.middleware.CustomMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "rangam_saradha_silk.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "home" / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                # Custom context processor
                "home.context_processors.global_context",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "rangam_saradha_silk.wsgi.application"


# ============================================================
# DATABASE - POSTGRESQL
# ============================================================

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

import sys
if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "test_db.sqlite3",
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

# Your source static directory
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# collectstatic destination
STATIC_ROOT = BASE_DIR / "staticfiles"


# ============================================================
# MEDIA / CLOUDINARY
# ============================================================

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
}


MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# DJANGO 5.2 STORAGE CONFIGURATION
# ============================================================

STORAGES = {
    # User uploaded files
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },

    # CSS / JS / admin static files
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# CUSTOM USER MODEL
# ============================================================

AUTH_USER_MODEL = "accounts.CustomUser"


# ============================================================
# LOGIN / LOGOUT
# ============================================================

LOGIN_REDIRECT_URL = "home:index"

LOGOUT_REDIRECT_URL = "home:index"

LOGIN_URL = "accounts:login"


# ============================================================
# GOOGLE AUTHENTICATION
# ============================================================

GOOGLE_CLIENT_ID = os.environ.get(
    "GOOGLE_CLIENT_ID",
    ""
)

GOOGLE_CLIENT_SECRET = os.environ.get(
    "GOOGLE_CLIENT_SECRET",
    ""
)


# ============================================================
# FIREBASE ADMIN SDK
# ============================================================

import firebase_admin
from firebase_admin import credentials


FIREBASE_KEY_PATH = os.environ.get(
    "FIREBASE_CREDENTIALS_PATH",
    str(
        BASE_DIR
        / "rangam-saradha-silks-firebase-adminsdk-fbsvc-ef25e865c8.json"
    ),
)


if not firebase_admin._apps:

    if os.path.exists(FIREBASE_KEY_PATH):

        try:
            cred = credentials.Certificate(FIREBASE_KEY_PATH)

            firebase_admin.initialize_app(cred)

        except Exception as e:
            print(
                f"Firebase Admin initialization error: {e}"
            )

    else:

        try:
            firebase_admin.initialize_app()

        except Exception as e:
            print(
                f"Firebase default initialization error: {e}"
            )


# ============================================================
# FIREBASE WEB CONFIGURATION
# ============================================================

FIREBASE_CONFIG = {
    "apiKey": os.environ.get(
        "FIREBASE_API_KEY",
        ""
    ),

    "authDomain": os.environ.get(
        "FIREBASE_AUTH_DOMAIN",
        "rangam-saradha-silks.firebaseapp.com",
    ),

    "projectId": os.environ.get(
        "FIREBASE_PROJECT_ID",
        "rangam-saradha-silks",
    ),

    "storageBucket": os.environ.get(
        "FIREBASE_STORAGE_BUCKET",
        "rangam-saradha-silks.appspot.com",
    ),

    "messagingSenderId": os.environ.get(
        "FIREBASE_MESSAGING_SENDER_ID",
        "",
    ),

    "appId": os.environ.get(
        "FIREBASE_APP_ID",
        "",
    ),
}


# ============================================================
# PRODUCTION SECURITY
# ============================================================

if not DEBUG:

    # HTTPS behind Nginx / reverse proxy
    USE_X_FORWARDED_HOST = True

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_CONTENT_TYPE_NOSNIFF = True

    X_FRAME_OPTIONS = "DENY"

    # Production CSRF trusted origins
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get(
            "CSRF_TRUSTED_ORIGINS",
            ""
        ).split(",")
        if origin.strip()
    ]


# ============================================================
# TWILIO VERIFY
# ============================================================

TWILIO_ACCOUNT_SID = os.environ.get(
    "TWILIO_ACCOUNT_SID",
    ""
)

TWILIO_AUTH_TOKEN = os.environ.get(
    "TWILIO_AUTH_TOKEN",
    ""
)

TWILIO_VERIFY_SERVICE_SID = os.environ.get(
    "TWILIO_VERIFY_SERVICE_SID",
    ""
)


# ============================================================
# EMAIL CONFIGURATION
# ============================================================

EMAIL_HOST = os.environ.get(
    "EMAIL_HOST",
    "smtp.gmail.com",
)

EMAIL_PORT = int(
    os.environ.get(
        "EMAIL_PORT",
        587,
    )
)

EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    "",
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    "",
)

EMAIL_USE_TLS = (
    os.environ.get(
        "EMAIL_USE_TLS",
        "True",
    ).lower()
    == "true"
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER,
)


# Development email behaviour
if DEBUG and not EMAIL_HOST_USER:

    EMAIL_BACKEND = (
        "django.core.mail.backends.console.EmailBackend"
    )

else:

    EMAIL_BACKEND = (
        "django.core.mail.backends.smtp.EmailBackend"
    )


# ============================================================
# GOOGLE IDENTITY SERVICES / OAUTH
# ============================================================

SECURE_CROSS_ORIGIN_OPENER_POLICY = (
    "same-origin-allow-popups"
)